spring:
  datasource:
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create

    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
