spring:
  datasource:

    initialization-mode: always



  jpa:
    hibernate:
      ddl-auto: create

    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect