insert into authors values (1, 'Igor');
insert into authors values (2, 'Max');
insert into authors values (3, 'Alex');
insert into authors values (4, 'Pit');
insert into authors values (5, 'Pavel');

INSERT into documents (author_id, creating_date, description, document_name, subject, end_date) values (1, '200101', 'Lorem ipsum .', 'document1', 'Peter', '200105');
INSERT into documents(author_id,creating_date, description, document_name,  subject, end_date) values (2, '200101', 'Lorem ipsum .', 'document1', 'Peter', '200105');
 INSERT into documents(author_id,creating_date, description, document_name,  subject, end_date) values (3, '200102', 'Lorem ipsum .', 'document2', 'Leonard', '200106');
 INSERT into documents(author_id,creating_date, description, document_name,  subject, end_date) values (4, '200103', 'Lorem ipsum .', 'document3', 'Peter', '200107');
 INSERT into documents(author_id,creating_date, description, document_name,  subject, end_date) values (2, '200104', 'Lorem ipsum .', 'document4', 'Peter', '200108');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (5, '200105', 'Lorem ipsum .', 'document5', 'Peter', '200109');
 INSERT into documents(author_id,creating_date, description, document_name,  subject, end_date) values (1, '200106', 'Lorem ipsum .', 'document6','Victor', '200110');
 INSERT into documents(author_id, creating_date,description, document_name,  subject, end_date) values (2, '200107', 'Lorem ipsum .', 'document7', 'Peter', '200111');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (3, '200108', 'Lorem ipsum .', 'document8','Leonard', '200112');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (2, '200109', 'Lorem ipsum .', 'document9','Kate', '200113');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (4, '200110', 'Lorem ipsum .', 'document10', 'Peter', '200114');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (5, '200111', 'Lorem ipsum .', 'document11', 'Peter', '200115');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (2, '200112', 'Lorem ipsum .', 'document12','Leonard', '200116');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (1, '200112', 'Lorem ipsum .', 'document50', 'Peter', '200117');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (2, '200113', 'Lorem ipsum .', 'document48', 'Kate', '200118');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (2, '200114', 'Lorem ipsum .', 'document49', 'Peter', '200119');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (3, '200115', 'Lorem ipsum .', 'document45', 'Leonard', '200120');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (4, '200116', 'Lorem ipsum .', 'document46', 'Peter', '200121');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (2, '200117', 'Lorem ipsum .', 'document47', 'Kate', '200122');
 INSERT into documents(author_id, creating_date, description, document_name, subject, end_date) values (5, '200118', 'Lorem ipsum .', 'document37','Leonard', '200123');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (1, '200119', 'Lorem ipsum .', 'document36','Kate', '200124');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (2, '200120', 'Lorem ipsum .', 'document44', 'Peter', '200125');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (3, '200121', 'Lorem ipsum .', 'document33', 'Kate', '200126');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (2, '200122', 'Lorem ipsum .', 'document34', 'Peter', '200127');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (4, '200123', 'Lorem ipsum .', 'document35', 'Leonard', '200128');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (5, '200124', 'Lorem ipsum .', 'document38', 'Peter', '200129');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (2, '200125', 'Lorem ipsum .', 'document43','Kate', '200130');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (1, '200126', 'Lorem ipsum .', 'document39', 'Peter', '200201');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (3, '200127', 'Lorem ipsum .', 'document42','Leonard', '200202');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (2, '200201', 'Lorem ipsum .', 'document40', 'Peter', '200203');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (4, '200202', 'Lorem ipsum .', 'document29', 'Peter', '200204');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (5, '200203', 'Lorem ipsum .', 'document41', 'Leonard', '200205');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (1, '200204', 'Lorem ipsum .', 'document30','Kate', '200206');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (2, '200205', 'Lorem ipsum .', 'document31','Leonard', '200207');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (3, '200206', 'Lorem ipsum .', 'document32', 'Kate', '200208');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (4, '200207', 'Lorem ipsum .', 'document22','Leonard', '200209');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (5, '200208', 'Lorem ipsum .', 'document23', 'Peter', '200210');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (1, '200209', 'Lorem ipsum .', 'document24', 'Peter', '200211');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (2, '200210', 'Lorem ipsum .', 'document20','Kate', '200212');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (3, '200211', 'Lorem ipsum .', 'document21', 'Kate', '200213');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (4, '200212', 'Lorem ipsum .', 'document19', 'Leonard', '200214');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (5, '200213', 'Lorem ipsum .', 'document26', 'Peter', '200215');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (1, '200214', 'Lorem ipsum .', 'document25','Kate', '200216');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (2, '200215', 'Lorem ipsum .', 'document18','Leonard', '200217');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (3, '200216', 'Lorem ipsum .', 'document27','Kate', '200218');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (4, '200217', 'Lorem ipsum .', 'document28', 'Peter', '200219');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (5, '200218', 'Lorem ipsum .', 'document17', 'Peter', '200220');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (1, '200219', 'Lorem ipsum .', 'document14', 'Leonard', '200221');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (2, '200220', 'Lorem ipsum .', 'document15', 'Kate', '200222');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (3, '200221', 'Lorem ipsum .', 'document16','Kate', '200223');
 INSERT into documents(author_id, creating_date, description, document_name,  subject, end_date) values (4, '200222', 'Lorem ipsum .', 'document13', 'Peter', '200224');
